package com.example.gen;

// Generated by annotation processor: do not edit.
public class GeneratedModel {
    public String getId() {
        return "id";
    }

    public void setId(String id) {
    }
}
