use kaptaind::config::loader::Config;
use kaptaind::util::style::*;
use std::fs;
use std::path::Path;

pub fn handle_init(config: &Config) -> anyhow::Result<()> {
    let root = &config.repo_path;

    // Don't overwrite existing config
    let toml_path = root.join("kaptaind.toml");
    if toml_path.exists() {
        println!(
            "{} {}",
            "⚠️".yellow(),
            "kaptaind.toml already exists. Skipping.".yellow()
        );
        return Ok(());
    }

    let project = detect_project_type(root);

    // Generate kaptaind.toml
    let toml_content = generate_toml(&project);
    fs::write(&toml_path, &toml_content)?;
    println!(
        "{} {} {}",
        "✅".green(),
        "Created".green(),
        "kaptaind.toml".bold()
    );

    // Generate .kaptainignore
    let ignore_path = root.join(".kaptainignore");
    if !ignore_path.exists() {
        let ignore_content = generate_ignore(&project);
        fs::write(&ignore_path, &ignore_content)?;
        println!(
            "{} {} {}",
            "✅".green(),
            "Created".green(),
            ".kaptainignore".bold()
        );
    } else {
        println!(
            "{} {}",
            "⚠️".yellow(),
            ".kaptainignore already exists. Skipping.".yellow()
        );
    }

    println!(
        "\n{} {} {}",
        "🎯".cyan(),
        "Detected project type:".cyan(),
        format!("{:?}", project).bold().magenta()
    );

    // Register project for autostart/monitoring
    let _ = kaptaind::monitor::add(root, None, None, Some(true));

    Ok(())
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ProjectType {
    Rust,
    Node,
    Python,
    Go,
    Swift,
    Kotlin,
    Unknown,
}

fn detect_project_type(root: &Path) -> ProjectType {
    if root.join("Cargo.toml").exists() {
        ProjectType::Rust
    } else if root.join("Package.swift").exists() {
        ProjectType::Swift
    } else if root.join("build.gradle.kts").exists() || root.join("build.gradle").exists() {
        ProjectType::Kotlin
    } else if root.join("package.json").exists() {
        ProjectType::Node
    } else if root.join("pyproject.toml").exists() || root.join("requirements.txt").exists() {
        ProjectType::Python
    } else if root.join("go.mod").exists() {
        ProjectType::Go
    } else {
        ProjectType::Unknown
    }
}

fn generate_toml(project: &ProjectType) -> String {
    let (test_cmd, weights) = match project {
        ProjectType::Rust => ("cargo test", "s = 0.35\na = 0.30\nd = 0.20\nr = 0.15"),
        ProjectType::Node => ("npm test", "s = 0.30\na = 0.35\nd = 0.20\nr = 0.15"),
        ProjectType::Python => ("pytest", "s = 0.35\na = 0.30\nd = 0.20\nr = 0.15"),
        ProjectType::Go => ("go test ./...", "s = 0.35\na = 0.30\nd = 0.20\nr = 0.15"),
        ProjectType::Swift => ("swift test", "s = 0.35\na = 0.30\nd = 0.20\nr = 0.15"),
        ProjectType::Kotlin => ("./gradlew test", "s = 0.35\na = 0.30\nd = 0.20\nr = 0.15"),
        ProjectType::Unknown => (
            "echo 'no test command configured'",
            "s = 0.35\na = 0.30\nd = 0.20\nr = 0.15",
        ),
    };

    format!(
        r#"# kaptaind configuration — auto-generated by `kaptaind-cli init`

[watch]
path = "."
recursive = true
ignore_file = ".kaptainignore"

[cluster]
window = 5
# max_paths = 0      # flush cluster after N events (0 = disabled)
# flush_after = 10   # idle timeout in seconds (defaults to window)

[weights]
{weights}

[push]
enabled = false
branch = "main"

[ratelimit]
min_commit_interval = 10

[test]
command = "{test_cmd}"
required = true

# [staging]
# mode = "all"        # "all" (default), "cluster" (only changed files), or "pattern"
# include = ["src/**"] # only used in "pattern" mode
# exclude = ["*.log", ".env*"]

# [deckhand]
# enabled = false              # enable automatic storage management
# interval_minutes = 360       # how often to run (default: 6 hours)
# sweep_keep_days = 30         # keep registry/git cache entries newer than N days
# clean_profiles = ["debug"]   # cargo profiles to clean
# clean_older_than_days = 14   # only clean artifacts older than N days (optional)
# dry_run = false              # only report what would be removed
# min_free_percent = 10        # skip pass when more than this % of disk is free

# [shark]
# enabled = false              # enable Shark Stating high availability
# arbiter_path = ".kaptaind/shark"  # shared directory for leadership leases
# heartbeat_interval_ms = 1000 # how often to renew/inspect lease
# heartbeat_timeout_ms = 5000  # how long to wait before considering leader dead
# lease_ttl_ms = 10000         # lease expiration time
# instance_id = "kaptaind-a"   # stable identifier for this instance
# upgrade_handoff_timeout_ms = 30000
# mode = "auto"                # "auto", "leader", "standby", or "observer"
"#
    )
}

fn generate_ignore(project: &ProjectType) -> String {
    let mut lines = vec![
        "# Common",
        ".git",
        ".kaptaind",
        ".DS_Store",
        "*.swp",
        "*.swo",
    ];

    match project {
        ProjectType::Rust => {
            lines.extend(["", "# Rust", "target"]);
        }
        ProjectType::Node => {
            lines.extend([
                "",
                "# Node",
                "node_modules",
                ".next",
                "dist",
                "build",
                ".turbo",
                ".vercel",
                ".output",
                "*.lock",
            ]);
        }
        ProjectType::Python => {
            lines.extend([
                "",
                "# Python",
                "__pycache__",
                ".venv",
                ".pytest_cache",
                "*.egg-info",
                "dist",
            ]);
        }
        ProjectType::Go => {
            lines.extend(["", "# Go", "vendor"]);
        }
        ProjectType::Swift => {
            lines.extend([
                "",
                "# Swift",
                ".build",
                "DerivedData",
                "*.xcodeproj/xcuserdata",
                "*.xcworkspace/xcuserdata",
                "Pods",
            ]);
        }
        ProjectType::Kotlin => {
            lines.extend([
                "",
                "# Kotlin/Gradle",
                "build",
                ".gradle",
                "*.iml",
                ".idea",
                "local.properties",
            ]);
        }
        ProjectType::Unknown => {}
    }

    lines.push(""); // trailing newline
    lines.join("\n")
}
